# Render deployment configuration for Face Recognition Attendance System Frontend Only
# This file defines only the frontend service for simpler deployment

services:
  # Frontend Static Site (Next.js)
  - type: web
    name: face-recognition-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    envVars:
      - key: NODE_VERSION
        value: "18.17.0"
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        sync: false # Set this in Render dashboard
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        sync: false # Set this in Render dashboard
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        sync: false # Set this in Render dashboard
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        sync: false # Set this in Render dashboard
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        sync: false # Set this in Render dashboard
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        sync: false # Set this in Render dashboard
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false # Set this in Render dashboard
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false # Set this in Render dashboard
      - key: NEXT_PUBLIC_API_URL
        sync: false # Set this to your backend URL
